"""added last login field to user

Revision ID: 219dba055234
Revises: c4b2d0f0b2a0
Create Date: 2020-07-12 22:14:23.092257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219dba055234'
down_revision = 'c4b2d0f0b2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
