"""empty message

Revision ID: c4b2d0f0b2a0
Revises: a3852a8abc2e
Create Date: 2020-07-07 17:50:42.585209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b2d0f0b2a0'
down_revision = 'a3852a8abc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('intro', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'intro')
    # ### end Alembic commands ###
